### ISSUE TITLE
generate fr and de - 25017

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/storagegrid-116#22]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by ntap-bmegan** [comment]
@netapp-gudugunti - @netapp-lhalbert ran a proactive build to disable some error checking ahead of the French/German work because of the repo size, but that build failed. I'm looking into it. I'm not sure what your target date for this repo is, but can you back-burner it until we've resolved the other problem?

**Comment by netapp-gudugunti** [comment]
Sure @ntap-bmegan. Have not set any target date. Shall move it down in the queue.

**Comment by ntap-bmegan** [comment]
German and French are up, and the repos are configured. Total TOT: 3 hours
