### ISSUE TITLE
The item "What is the Destination?" should be updated with GCP 

### ISSUE THREAD

**Issue by ntap-leeray** [NetAppDocs/storagegrid-116#3]
Page: [Comparing Cloud Storage Pools and CloudMirror replication](https://docs.netapp.com/us-en/storagegrid-116/ilm/comparing-cloud-storage-pools-to-cloudmirror-replication.html)

As titled, we now support GCP for both CSP and CloudMirror.

**Comment by netapp-madkat** [comment]
Hi, 
After I replied, I saw the big bold title with the details about what you need us to change. You can ignore my first reply. 

I've created a doc mantis to track this: 
https://bugtracking.vtc.eng.netapp.com/mantis/view.php?id=42538 

Thank you again for bringing this oversight to our attention.

kathy

**Comment by ntap-bmegan** [comment]
@netapp-madkat - Can this issue be closed?

**Comment by netapp-madkat** [comment]
I'm not sure. It depends on how we are defining what it means to close an issue. This was one of the first requests we got for 11.6 and I created a mantis (similar to a burt), which is still open for 11.7 (that release won't be available until early 2023). So is this issue now closed because I created the mantis or would closing it require making the change available on docs.netapp.com?

**Comment by netapp-madkat** [comment]
Hi @ntap-leeray 

Sorry for the delay. We are making your requested change for Google Cloud Platform (GCP) in the upcoming StorageGRID doc site. We will update the 11.6 doc site as time allows.

Thank you again for helping us to improve the quality of our documentation.

Kathy
