### ISSUE TITLE
SSH fingerprint error after node replacement

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-116#33]
Page: [Replace SG6000-CN controller](https://docs.netapp.com/us-en/storagegrid-116/sg6000/replacing-sg6000-cn-controller.html)

Following a node replacement, we had a customer attempt a hotfix upgrade which failed due to SSH key / fingerprint being incorrect. The customer had to SSH into admin node and re-generate key ssh-keygen in order to resolve the issue. 

Fingerprint change is not covered in node replacement process. Should this be included in the process? And any software improvement available to automatically update fingerprint.

"Fingerprint does not match”
“Error: Unable to connect to NODE_XX on port 22: fingerprint SHA256:VfO57lTwteMYRKPvTK8N3rQWx8Jnig/7AmRQ15sJBHw does not match for "NODE_XX,%%.%%.%%.%%"”

**Comment by netapp-madkat** [comment]
Hi @ahmadm-netapp,

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @ahmadm-netapp,

I am closing this issue because we have now created a bug report to further investigate how to address the issue.  Our experts indicate that running ssh-keygen is not the recommended solution.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)
