### ISSUE TITLE
Certificate installation

### ISSUE THREAD

**Issue by kmcreyno** [NetAppDocs/storagegrid-116#34]
Page: [Configure S3 and Swift API certificates](https://docs.netapp.com/us-en/storagegrid-116/admin/configuring-custom-server-certificate-for-storage-node-or-clb.html)

I would like to request the Generate CSR be incorporated to the upload cert/cert generation part of this article:
https://github.com/NetApp-StorageGRID/SSL-Certificate-Configuration

Also if we can link the load balancer endpoint configuration doc to cover how to install a cert on the endpoint if used:
https://docs.netapp.com/us-en/storagegrid-116/admin/configuring-load-balancer-endpoints.html

**Comment by netapp-madkat** [comment]
Hi @kmcreyno 

Thank you for bringing this to our attention. We will look into it and determine how best to address it.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @kmcreyno 

I am closing this issue because we have now created a bug report to further investigate how to address the issue in the next release of the doc site.

Thanks again for helping us improve the quality of our documentation.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)
