### ISSUE TITLE
Process does not include steps to shut down the SG6000 node

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-116#36]
Page: [Replace Fibre Channel HBA in SG6000-CN controller](https://docs.netapp.com/us-en/storagegrid-116/sg6000/replacing-fibre-channel-hba-in-sg6000-cn-controller.html)

The HBA replacement process does not include the steps to shut down  or power on the node. It only covers verifying the node to be services and the steps to remove then re-install the HBA. The same procedure document is used in NET2 for field support.

**Comment by netapp-madkat** [comment]
Hi @ahmadm-netapp 

Thank you for bringing this to our attention. As it turns out, this is the second request we've received to make this change (see also https://github.com/NetAppDocs/storagegrid-116/issues/24). We're currently making the suggested fix for our upcoming StorageGRID release and will fix it in the StorageGRID 11.6 doc site as soon as we can.

Kathy Maddox
Content architect
StorageGRID Information Engineering (IE)

**Comment by netapp-madkat** [comment]
Hi @ahmadm-netapp 

We have now made the change to the 11.6 doc site as well. Please see the new bullet in What you'll need here: https://docs.netapp.com/us-en/storagegrid-116/sg6000/removing-fibre-channel-hba.html

Thank you again for bringing this to our attention,

Kathy

**Comment by ahmadm-netapp** [comment]
Thank you @netapp-madkat for the update. Looks good.
