### ISSUE TITLE
Purpose of Stored object hashing is not clear

### ISSUE THREAD

**Issue by vardhanv** [NetAppDocs/storagegrid-116#59]
### Page URL

https://docs.netapp.com/us-en/storagegrid-116/admin/configuring-stored-object-hashing.html

### Page title

Configure stored object hashing

### Summary

The current doc says
"The Stored Object Hashing option specifies the hashing algorithm used to verify object integrity."

It is unclear who is verifying this object integrity, and what happens when it is not met.

In particular this is confusing when read along with 
https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by vardhanv** [comment]
I believe the answer is something like -
This is used to check for integrity of data at rest in SG, While the AWS S3 APIs are for integrity between the client and SG⁠

**Comment by netapp-madkat** [comment]
Hi Vishnu, 

Thank you for your comment and explanation. As it turns out, the Stored Object Hashing option was removed in StorageGRID 11.7. Here's what we said about that option in the `[Removed and deprecated features](https://docs.netapp.com/us-en/storagegrid-117/upgrade/removed-or-deprecated-features.html#grid-manager-options-moved-or-removed)` section of the 11.7 Upgrade Guide:

> The Stored Object Hashing option was removed. The SHA-1 and SHA-256 settings are no longer used for internal background verification because they require additional CPU resources over MD5 and packet CRC32 check.

While your concern for 11.6 is valid, unfortunately we won't have time to update that doc site. Thank you for your understanding.

Kathy Maddox
Principal technical writer
StorageGRID information engineering
