### ISSUE TITLE
Metric storagegrid_storage_utilization_metadata_bytes listed twice

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/storagegrid-116#9]
Page: [Commonly used Prometheus metrics](https://docs.netapp.com/us-en/storagegrid-116/monitor/commonly-used-prometheus-metrics.html)

The metric named storagegrid_storage_utilization_metadata_bytes is listed twice in the table of common metrics to monitor.

I strongly suspect the first occureance SHOULD be to storagegrid_storage_utilization_data_bytes, given the description in the right hand column.

**Comment by ntap-bmegan** [comment]
@netapp-madkat - Please update status or close if work is complete.

**Comment by netapp-madkat** [comment]
Hi @estarz,

Your strong suspicion was correct. The first instance of that metric name in the table should have been storagegrid_storage_utilization_data_bytes instead of storagegrid_storage_utilization_metadata_bytes. I have updated the name  in our draft doc site for the next release, and we are tracking this change for our next update of the StorageGRID 11.6 doc site. 

Thank you for letting us know.

Kathy
